ARG IMAGE
FROM ${IMAGE}

RUN mkdir /function && \
  pip install --target /function awslambdaric
COPY app.py /function
WORKDIR /function

ENTRYPOINT ["/usr/bin/python3", "-m", "awslambdaric" ]

CMD [ "app.handler" ]