# FROM zmkfirmware/zmk-dev-arm:3.5
ARG IMAGE
FROM ${IMAGE}

ENV HOME="/zmk-firmware"

# zmk
RUN mkdir /zmk-firmware/config  -p
COPY config /zmk-firmware/config
WORKDIR /zmk-firmware
RUN west init -l /zmk-firmware/config/ && west update 
COPY build_fish.py /zmk-firmware
RUN chmod +x /zmk-firmware/build_fish.py
# ENV ZEPHYR_BASE=/zmk-firmware

CMD [ "/bin/bash" ]